version: "3.8"

services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
   
  mythril:
    image: mythril/myth:latest
    volumes:
      - ./contracts:/contracts
    depends_on:
      - ganache
    command: ${MYTHRIL_COMMAND:-"version"}
      
  truffle:
    build:
      context: .
      target: truffle
    depends_on:
      - mythril
      - ganache
    command: ${TRUFFLE_COMMAND}





