name: Particle CI

on:
  # Temporarily disable all triggers
  workflow_dispatch: # Only manual triggers allowed, comment out to re-enable automatic triggers
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:   
      # Step 1: Check out code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Compile contracts
      - name: Compile contracts
        run: npx hardhat compile

      # Step 5: Run tests
      - name: Run tests
        run: npx hardhat test

      # Step 6: Run solhint
      - name: Run solhint
        run: npx solhint 'contracts/**/*.sol'

      # Step 7: Run slither
      - name: Install Slither
        run: |
          python3 -m pip install --user slither-analyzer
          
      - name: Run Slither
        run: slither . --exclude-dependencies

      # Step 8: Run Mythril analysis
      - name: Install Mythril
        run: |
          python3 -m pip install mythril

      - name: Run Mythril
        run: |
          find contracts -name "*.sol" -not -path "contracts/test/*" -not -path "contracts/mock/*" -exec myth analyze {} --execution-timeout 300 \;
